apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hcloudmachines
  labels:
    cluster.x-k8s.io/aggregate-to-manager: "true"
rules:
- apiGroups:
  - cluster-api-provider-hcloud.capihc.com
  resources:
  - hcloudmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
