
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - cluster-api-provider-hcloud.capihc.com
  resources:
  - hcloudclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster-api-provider-hcloud.capihc.com
  resources:
  - hcloudclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster-api-provider-hcloud.capihc.com
  resources:
  - hcloudmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster-api-provider-hcloud.capihc.com
  resources:
  - hcloudmachines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster-api-provider-hcloud.capihc.com
  resources:
  - baremetalmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster-api-provider-hcloud.capihc.com
  resources:
  - baremetalmachines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster-api-provider-hcloud.capihc.com
  resources:
  - hcloudvolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster-api-provider-hcloud.capihc.com
  resources:
  - hcloudvolumes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  - clusters/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machines
  - machines/status
  verbs:
  - get
  - list
  - watch
