apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeadm-control-plane-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeadm-control-plane-manager
subjects:
- kind: Group
  name: system:serviceaccounts:capi-kubeadm-control-plane-system
  apiGroup: rbac.authorization.k8s.io
