apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeadm-control-plane-manager
rules:
- apiGroups:
  - cluster-api-provider-hcloud.capihc.com
  resources:
  - hcloudmachinetemplates
  - hcloudmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
