apiVersion: cluster-api-provider-hcloud.swine.dev/v1alpha3
kind: HcloudCluster
metadata:
  name: cluster-dev
spec:
  location: nbg1
  tokenRef:
    name: hcloud-token
    key: token
  sshKeys:
    - name: id_rsa
  controlPlaneFloatingIPs:
    - type: IPv4
---
apiVersion: cluster.x-k8s.io/v1alpha2
kind: Cluster
metadata:
  name: cluster-dev
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["172.16.0.0/12"]
    pods:
      cidrBlocks: ["192.168.0.0/16"]
    serviceDomain: "cluster.local"
  infrastructureRef:
    apiVersion: cluster-api-provider-hcloud.swine.dev/v1alpha3
    kind: HcloudCluster
    name: cluster-dev
