apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
kind: KubeadmConfig
metadata:
  name: controller
spec:
  initConfiguration:
    nodeRegistration:
      kubeletExtraArgs:
        cloud-provider: external
  clusterConfiguration:
    apiServer:
      extraArgs:
        cloud-provider: external
    controllerManager:
      extraArgs:
        cloud-provider: external
#TODO kubelet config
# rotateCertificates: true
# serverTLSBootstrap: true
---
apiVersion: cluster-api-provider-hcloud.swine.dev/v1alpha3
kind: HcloudMachine
metadata:
  name: controller
spec:
  location: nbg1
  type: cx21
  volumes:
    - name: etcd
      mountPath: /var/lib/etcd
      volumeRef: controller-etcd
---
apiVersion: cluster.x-k8s.io/v1alpha2
kind: Machine
metadata:
  name: controller
  labels:
    cluster.x-k8s.io/cluster-name: cluster-dev
    cluster.x-k8s.io/control-plane: "true"
spec:
  version: "v1.16.7"
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
      kind: KubeadmConfig
      name: controller
  infrastructureRef:
    apiVersion: cluster-api-provider-hcloud.swine.dev/v1alpha3
    kind: HcloudMachine
    name: controller
---
apiVersion: cluster-api-provider-hcloud.swine.dev/v1alpha3
kind: HcloudVolume
metadata:
  name: controller-etcd
  labels:
    cluster.x-k8s.io/cluster-name: cluster-dev
spec:
  size: 16Gi
  location: nbg1
  reclaimPolicy: Delete
