apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: HetznerCluster
metadata:
  name: cluster-dev
spec:
  location: nbg1
  tokenRef:
    name: hcloud-token
    key: token
  controlPlaneFloatingIPs:
    - type: IPv4
    - type: IPv6
---
apiVersion: v1
kind: Secret
metadata:
  name: hcloud-token
type: Opaque
stringData:
  token: {ISHOULDBEATOKEN}
---
apiVersion: cluster.x-k8s.io/v1alpha2
kind: Cluster
metadata:
  name: cluster-dev
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["172.16.0.0/12"]
    pods:
      cidrBlocks: ["192.168.0.0/16"]
    serviceDomain: "cluster.local"
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: HetznerCluster
    name: cluster-dev
