apiVersion: cluster-api-provider-hcloud.capihc.com/v1alpha3
kind: HcloudCluster
metadata:
  name: cluster-dev
spec:
  locations:
    - nbg1
  tokenRef:
    name: hcloud-token
    key: token
  sshKeys:
    - name: id_rsa
  controlPlaneLoadBalancers:
  - type: lb11
    algorithm: round_robin
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: cluster-dev
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["172.16.0.0/12"]
    pods:
      cidrBlocks: ["192.168.0.0/16"]
    serviceDomain: "cluster.local"
  infrastructureRef:
    apiVersion: cluster-api-provider-hcloud.capihc.com/v1alpha3
    kind: HcloudCluster
    name: cluster-dev
  controlPlaneRef:
    kind: KubeadmControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    name: cluster-dev
