apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineDeployment
metadata:
  name: cluster-dev-worker
  labels:
    nodepool: worker
spec:
  replicas: 2
  clusterName: cluster-dev
  selector:
    matchLabels:
      nodepool: worker
  template:
    metadata:
      labels:
        nodepool: worker
    spec:
      clusterName: cluster-dev
      version: "v1.17.5"
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: KubeadmConfigTemplate
          name: cluster-dev-worker
      infrastructureRef:
        apiVersion: cluster-api-provider-hcloud.swine.dev/v1alpha3
        kind: HcloudMachineTemplate
        name: cluster-dev-worker
      failureDomain: nbg1
---
apiVersion: cluster-api-provider-hcloud.swine.dev/v1alpha3
kind: HcloudMachineTemplate
metadata:
  name: cluster-dev-worker
spec:
  template:
    spec:
      type: cpx11
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: KubeadmConfigTemplate
metadata:
  name: cluster-dev-worker
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external
