name: CI

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Mount bazel cache
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel

    - name: Install bazelisk
      run: |
        mkdir -p "${GITHUB_WORKSPACE}/bin"
        curl -Lo "${GITHUB_WORKSPACE}/bin/bazel" "https://github.com/bazelbuild/bazelisk/releases/download/v1.3.0/bazelisk-linux-amd64"
        echo "98af93c6781156ff3dd36fa06ba6b6c0a529595abb02c569c99763203f3964cc  ${GITHUB_WORKSPACE}/bin/bazel" | sha256sum -c
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
    - name: Test
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" test //...

    - name: Build
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" build //...
